# Generated by Django 3.2.16 on 2023-01-04 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddedOptionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('price', models.FloatField()),
                ('stars', models.IntegerField()),
                ('description', models.TextField()),
                ('seats', models.IntegerField()),
                ('bags', models.IntegerField()),
                ('doors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('Protection', 'Protection'), ('Additional', 'Additional')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=500)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_datetime', models.DateTimeField(blank=True, null=True)),
                ('return_location', models.CharField(blank=True, choices=[('International Airport', 'International Airport'), ('Delivery Service', 'Delivery Service'), ('Our Main Office', 'Our Main Office')], max_length=50, null=True)),
                ('pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('pickup_location', models.CharField(blank=True, choices=[('International Airport', 'International Airport'), ('Delivery Service', 'Delivery Service'), ('Our Main Office', 'Our Main Office')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ORDERED', 'ORDERED'), ('COMPLETE', 'COMPLETE'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=50)),
                ('car_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cars.cardesign')),
                ('options', models.ManyToManyField(blank=True, related_name='orders', through='cars.AddedOptionInfo', to='cars.Option')),
            ],
        ),
    ]
