# Generated by Django 3.2.16 on 2022-12-18 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('description', models.TextField()),
                ('image_urls', models.JSONField()),
                ('seats', models.IntegerField()),
                ('bags', models.IntegerField()),
                ('doors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField()),
                ('return_location', models.CharField(choices=[('International Airport', 'International Airport'), ('Delivery Service', 'Delivery Service'), ('Our Main Office', 'Our Main Office')], max_length=50)),
                ('pickup_date', models.DateTimeField()),
                ('pickup_location', models.CharField(choices=[('International Airport', 'International Airport'), ('Delivery Service', 'Delivery Service'), ('Our Main Office', 'Our Main Office')], max_length=50)),
                ('ordered', models.BooleanField(default=False)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cars.car')),
            ],
        ),
    ]
