# Generated by Django 3.2.16 on 2022-11-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('description', models.TextField()),
                ('image_urls', models.JSONField()),
                ('seats', models.IntegerField()),
                ('bags', models.IntegerField()),
                ('doors', models.IntegerField()),
            ],
        ),
    ]
