# Generated by Django 3.2.16 on 2022-12-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField()),
                ('return_location', models.CharField(choices=[('International Airport', 'International Airport'), ('Delivery Service', 'Delivery Service'), ('Our Main Office', 'Our Main Office')], max_length=50)),
                ('pickup_date', models.DateTimeField()),
                ('pickup_location', models.CharField(choices=[('International Airport', 'International Airport'), ('Delivery Service', 'Delivery Service'), ('Our Main Office', 'Our Main Office')], max_length=50)),
            ],
        ),
    ]
